### ISSUE TITLE
你好，你漏提交代码了吧

### ISSUE THREAD

**Issue by guojingwen** [jjeejj/movie-wechat#1]
所有index.js都没有提交，能提交一下吗，我也在研究scott老师的项目

git管理项目，web storm  开发的时候文件夹下面的index.js 提交不了处理办法

git add -f  wx/*/index.js

git add -f  app/*_/index.js
git add -f  wechat/_/index.js

**Comment by jjeejj** [comment]
我这个项目没有index.js文件的，这个是scott微信公众号的那个项目。
另外我用的sublime 没有遇到你说的提交不了的问题呢。
不过还是谢谢你的，有什么问题可以一起交流学习的。

**Comment by jjeejj** [comment]
> guojingwen
> 我这个项目没有index.js文件的，这个是scott微信公众号的那个项目。
> 另外我用的sublime 没有遇到你说的提交不了的问题呢。
> 不过还是谢谢你的，有什么问题可以一起交流学习的。
